

version: '3.8'

services: 
  finance_mysql:
    image: mysql:5.7.9
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db_config:/etc/mysql
      - db_data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    networks:
      - finance
      
  finance_api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: finance-api
    env_file: ./.env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    volumes: 
      - ./api:/api
      - /api/node_modules
    depends_on:
      - finance_mysql
    stdin_open: true
    tty: true
    networks:
      - finance

  finance_app:
    build:
      context: .
      dockerfile: ./app_server/Dockerfile
    image: finance-app
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    volumes: 
      - ./app_server:/app_server
      - /app_server/node_modules
    depends_on:
      - finance_mysql
    stdin_open: true
    tty: true
    networks:
      - finance

volumes: 
  db_config:
  db_data:

networks:
  finance: